// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StargateAPI.Business.Data;

#nullable disable

namespace StargateAPI.Business.Migrations
{
    [DbContext(typeof(StargateContext))]
    [Migration("20260305182228_UpdateSeedData")]
    partial class UpdateSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DutyEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DutyStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DutyTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasFilter("DutyEndDate IS NULL");

                    b.ToTable("AstronautDuty");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            DutyStartDate = new DateTime(2012, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "The White",
                            PersonId = 3,
                            Rank = "MAJ"
                        },
                        new
                        {
                            Id = 3,
                            DutyStartDate = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Pilot",
                            PersonId = 4,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 4,
                            DutyStartDate = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Explorer",
                            PersonId = 5,
                            Rank = "LT"
                        },
                        new
                        {
                            Id = 5,
                            DutyStartDate = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Scientist",
                            PersonId = 6,
                            Rank = "CIV"
                        },
                        new
                        {
                            Id = 6,
                            DutyStartDate = new DateTime(2018, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Engineer",
                            PersonId = 7,
                            Rank = "CIV"
                        },
                        new
                        {
                            Id = 7,
                            DutyEndDate = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Ringbearer",
                            PersonId = 8,
                            Rank = "ENS"
                        },
                        new
                        {
                            Id = 8,
                            DutyStartDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Operative",
                            PersonId = 9,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 9,
                            DutyStartDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Lord Commander",
                            PersonId = 10,
                            Rank = "CPT"
                        },
                        new
                        {
                            Id = 10,
                            DutyStartDate = new DateTime(1789, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "Treasurer",
                            PersonId = 11,
                            Rank = "MAJ"
                        },
                        new
                        {
                            Id = 11,
                            DutyEndDate = new DateTime(2012, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2011, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "The Grey",
                            PersonId = 3,
                            Rank = "MAJ"
                        },
                        new
                        {
                            Id = 12,
                            DutyEndDate = new DateTime(2019, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyStartDate = new DateTime(2018, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DutyTitle = "RETIRED",
                            PersonId = 10,
                            Rank = "CPT"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Gandolf"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cooper Howard"
                        },
                        new
                        {
                            Id = 5,
                            Name = "The Wander"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lucy Mcclain"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Barbara Howard"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Frodo Baggins"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Cassian Andor"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jon Snow"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Alexander Hamilton"
                        });
                });

            modelBuilder.Entity("StargateAPI.Business.Data.AstronautDuty", b =>
                {
                    b.HasOne("StargateAPI.Business.Data.Person", "Person")
                        .WithMany("AstronautDuties")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("StargateAPI.Business.Data.Person", b =>
                {
                    b.Navigation("AstronautDuties");
                });
#pragma warning restore 612, 618
        }
    }
}
